[package]
name = "libninja"
version = "0.1.9"
edition = "2021"
license = "MIT"
description = "Command line tool for OpenAPI client generation."
publish = false
default-run = "libninja"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
integration = []
actix = ["actix-web"]

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
log = "0.4.19"
proc-macro2 = "1.0.63"
quote = "1.0.28"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
serde_yaml = "0.9.22"
syn = "1.0.109"
tokio = { version = "1.28.2", features = ["full"] }
openapiv3-extended = { version = "2.2.1" }
convert_case = "0.6.0"
prettyplease = "0.1.25"
clap = { version = "4.3.8", features = ["derive"] }
tera = "1.19.0"
include_dir = "0.7.3"
regex = "1.8.4"
indoc = "2.0.1"
cargo_toml = "0.15.3"
toml = "0.7.5"
topo_sort = "0.4.0"
url = "2.4.0"
http = "0.2.9"
tracing-ez = "0.3.0"
strum = "0.24.1"
actix-web = { version = "4.3.1", optional = true }
semver = "1.0.17"
indexmap = "1.9.3"
lazy_static = "1"
ln-macro = { path = "../macro" }
ln-core = { path = "../core" }
ln-mir = { path = "../mir" }

[dev-dependencies]
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
tempfile = "3.6.0"
